# Sample config with required columns: sample_name, assay, run_type, [accession] OR [accession (any unique id), AND fastq_files]
  # Output files will be organized as {results}/{sample_name}/{assay}/{accession}.bam, etc.
sample_config: "config/TeloHAEC_metadata.tsv"

# Workflow params
results_dir: /oak/stanford/groups/engreitz/Projects/E2G/endothelial_cells/TeloHAEC_GSE210489_GSE210491
scratch_dir: /scratch/users/shethm/seq-processing-snakemake
sra_download: True
call_peaks: False

# Reference files
bowtie2_index: /oak/stanford/groups/engreitz/Users/sheth/hg38_resources/hg38_bowtie2_index

# Filtering parameters
mapq_threshold: 30

# Compute parameters
threads: 8
max_memory_allocation_mb: 250000 # for Sherlock, 250Gb


